models:
    min-workers: 1
    max-workers: 8
    batch-size: 8
    max-batch-delay: 1000
    retry-attempts: 2
    timeout-ms: 300000

    detection:
      url: craft.mar

    recognition:
      url: crnn.mar
      batch-size: 64

dag:
  pre_processing: [detection, recognition]
  detection: [recognition] 